In [9]:
import psycopg2
conn = psycopg2.connect(host='113.200.91.99',
                                    port=32654,
                                    user='execute_role',
                                    password= 'RQTsyd364&&udh',
                                    database='research_dep01',
                                    )
cursor = conn.cursor()
sql = "select movie_id,duration,tag_id,origin_id,final_rating,final_rating1,play_count from media_content.final;"

cursor.execute(sql)
results = cursor.fetchall()

ModuleNotFoundError: No module named 'psycopg2'

In [31]:
results

[('16906', '79.7167', '5', '213', 7.4, 7.4, '1224529'),
 ('8469', '121.15', '16', '225', 8.8, 8.8, '25989001'),
 ('7151', '89.3833', '12', '213', 6.4, 6.4, '2597001'),
 ('5871', '90.8333', '19', '213', 6.3, 6.3, '2019283'),
 ('45386', '100.7667', '3', '193', None, None, '1656876'),
 ('41825', '95.7667', '4', '124', 2.9, 2.9, '438388'),
 ('10655', '98.05', '3', '213', 7.1, 7.1, '1836962'),
 ('6788', '110.0333', '7', '124', 4.9, 4.9, '22250530'),
 ('55670', '108.1667', '31', '234', 6.7, 6.7, '3427814'),
 ('14159', '103.9', '12', '213', 7.6, 7.6, '582014'),
 ('60673', '114.5767', '19', '213', 7.3, 7.3, '1149734'),
 ('22730', '88.8833', '8', '124', 4.2, 4.2, '42745303'),
 ('41040', '119.95', '3', '194', 7.5, 7.5, '8344165'),
 ('22672', '104.2167', '15', '213', 6.4, 6.4, '1520857'),
 ('45484', '88.55', '8', '124', 4.2, 4.2, '8140249'),
 ('9441', '86.9167', '15', '234', 4.0, 4.0, '8985236'),
 ('22060', '0.5', '4', '124', 7.5, 7.5, '11517257'),
 ('6914', '89.9333', '8', '234', 5.2, 5.2, '1410

In [147]:
import numpy as np
x_data=np.zeros((len(results),5))
y_data=np.zeros((len(results),1))
for i in range(len(results)):
    if results[i][1]==None or results[i][2]==None or results[i][3]==None or results[i][4]==None or results[i][5]==None or  results[i][6]==None:
        x_data[i][0]=float(results[i-20][1])
        x_data[i][1]=float(results[i-20][2])
        x_data[i][2]=float(results[i-20][3])
        x_data[i][3]=7
        x_data[i][4]=7
        y_data[i]=float(results[i-20][6])
    else:
        x_data[i][0]=float(results[i][1])
        x_data[i][1]=float(results[i][2])
        x_data[i][2]=float(results[i][3])
        x_data[i][3]=float(results[i][4])
        x_data[i][4]=float(results[i][5])
        y_data[i]=float(results[i][6])

In [154]:
x_data

array([[ 79.7167,   5.    , 213.    ,   7.4   ,   7.4   ],
       [121.15  ,  16.    , 225.    ,   8.8   ,   8.8   ],
       [ 89.3833,  12.    , 213.    ,   6.4   ,   6.4   ],
       ...,
       [ 95.5167,  30.    , 193.    ,   7.    ,   7.    ],
       [ 85.5   ,   9.    , 234.    ,   6.3   ,   6.3   ],
       [101.9333,   3.    , 234.    ,   5.3   ,   5.3   ]])

In [155]:
y_data

array([[ 1224529.],
       [25989001.],
       [ 2597001.],
       ...,
       [ 4789915.],
       [ 3937148.],
       [22106192.]])

In [90]:
y_data=np.log(y_data)

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [95]:
y_data

array([[14.01806684],
       [17.07318397],
       [14.76986788],
       ...,
       [ 0.        ],
       [15.18596716],
       [16.91136831]])

In [1]:
from __future__ import print_function
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib

def add_layer(inputs, in_size, out_size, activation_function=None):
    Weights = tf.Variable(tf.random_normal([in_size, out_size]))
    biases = tf.Variable(tf.zeros([1, out_size]) + 0.1)
    Wx_plus_b = tf.matmul(inputs, Weights) + biases
    Wx_plus_b = tf.nn.dropout(Wx_plus_b, keep_prob)
    if activation_function is None:
        outputs = Wx_plus_b
    else:
        outputs = activation_function(Wx_plus_b)
    return outputs,Weights

def add_layer_out(inputs, in_size, out_size, activation_function=None):
    Weights = tf.Variable(tf.random_normal([in_size, out_size]))
    biases = tf.Variable(tf.zeros([1, out_size]) + 0.1)
    Wx_plus_b = tf.matmul(inputs, Weights) + biases
    if activation_function is None:
        outputs = Wx_plus_b
    else:
        outputs = activation_function(Wx_plus_b)
    return outputs,Weights

# Make up some real data
# noise = np.random.normal(0, 1, np.arange(0,1000,1).shape)
# x_data=np.ones((1000,5))
# x_data[:,0]=np.arange(0,1000,1)+100
# x_data[:,1]=np.arange(0,1000,1)/2
# x_data[:,2]=np.arange(0,1000,1)/5
# x_data[:,3]=np.arange(0,1000,1)*2
# x_data[:,4]=np.arange(0,1000,1)*2
# y_data=np.zeros((1000,1))
# y_data[:,0]=np.square(np.arange(0,1000,1)) + noise * 40
# for j in range(1000):
#     if j%2==1:
#         y_data[j,0]=0
#     else:
#         y_data[j,0]=1

# define placeholder for inputs to network
keep_prob = tf.placeholder(tf.float32)
xs = tf.placeholder(tf.float32, [None, 5])
ys = tf.placeholder(tf.float32, [None, 1])
# add hidden layer
l1,w1 = add_layer_out(xs, 5, 50, activation_function=tf.nn.relu)
l2,w2= add_layer_out(l1, 50, 50, activation_function=tf.nn.relu)
# add output layer
prediction,w_out = add_layer_out(l2, 50, 1, activation_function=None)

#Loss function
#loss = tf.reduce_mean(tf.reduce_sum(tf.square(ys-prediction), reduction_indices=[1]))
#loss = tf.reduce_mean((tf.square(ys-prediction)))

#loss=tf.reduce_mean(tf.squared_difference(ys, prediction))
#loss=tf.reduce_mean(tf.squared_difference(ys, prediction))
loss=tf.reduce_mean(tf.squared_difference(ys, prediction))+0.5*(tf.reduce_sum(tf.square(w1))+tf.reduce_sum(tf.square(w2)))
loss_2=tf.square(ys-prediction)

#Optimizer
#train_step = tf.train.GradientDescentOptimizer(0.1).minimize(loss)
#train_step=tf.train.MomentumOptimizer(0.05, 0.05).minimize(loss)
train_step=tf.train.RMSPropOptimizer(0.01).minimize(loss)



#Training
sess = tf.Session()
sess.run(tf.global_variables_initializer())

##plot the real data
# fig = plt.figure()
# ax = fig.add_subplot(1,1,1)
# ax.scatter(np.arange(0,1000,1), y_data,s=3)
# plt.ion()
# plt.show()
ans=[]
p=[]
for i in range(10000):
    # training
    #print((sess.run(prediction, feed_dict={xs: x_data, ys: y_data})))
    sess.run(train_step, feed_dict={xs: x_data, ys: y_data,keep_prob: 1})
    #print(sess.run(prediction, feed_dict={xs: x_data, ys: y_data}))
    #print('jjjjjjjjjjj')
    
    if i % 50 == 0:
        # to visualize the result and improvement
#         try:
#             ax.lines.remove(lines[0])
#         except Exception:
#             pass
        prediction_value = sess.run(prediction, feed_dict={xs: x_data, ys: y_data,keep_prob:1})
        # plot the prediction
        p.append(prediction_value)
#         lines = ax.scatter(np.arange(0,10,1), prediction_value)
#         plt.pause(1)
        ans.append(sess.run(loss, feed_dict={xs: x_data, ys: y_data,keep_prob: 1}))

#plt.scatter(list(range(1,len(ans)+1)),ans)

Using matplotlib backend: MacOSX
Instructions for updating:
Colocations handled automatically by placer.


In [7]:
p[100]

array([[0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],
       [0.6033304],


In [8]:
ans

[32500505000.0,
 31633784.0,
 371848.0,
 2397236.5,
 99708.72,
 848.871,
 478.72925,
 323.43286,
 158.58951,
 50.741215,
 14.418657,
 7.34216,
 3.638586,
 65240.535,
 25636.828,
 9.179981,
 4.7905374,
 3.610479,
 6.239855,
 2595.4973,
 6.842583,
 8.036866,
 4.922215,
 5.4047136,
 393.45996,
 6.3458266,
 6.7270813,
 4.0677543,
 3.9646506,
 6.584293,
 5.7605276,
 6.6717544,
 5.7032604,
 4.133546,
 5.274401,
 4.720836,
 6.293844,
 4.8351517,
 3.255959,
 3.2369606,
 5.5277247,
 4.234153,
 2.6215763,
 8.315183,
 7.888143,
 5.4552646,
 3.5292919,
 7.453548,
 7.128577,
 8.163833,
 7.1794043,
 3955417.2,
 5.031704,
 5.2628293,
 35019.207,
 5.207169,
 3.8531916,
 2405.392,
 3.96729,
 6.2595177,
 4.291943,
 3.0277371,
 5.1546116,
 6.255638,
 6.2683086,
 4.3587055,
 10.97224,
 5.18901,
 3.8841019,
 3.605692,
 3.9677532,
 5.0050235,
 7.7492285,
 6.189604,
 33115.75,
 8550.508,
 5.6038523,
 653.91724,
 3.4161506,
 2.0576096,
 7.42295,
 5.4343934,
 7.886477,
 4.451533,
 6.186459,
 54.949512,
 2.1392